server:
  port: 8081

spring:
  application:
    name: pendataan
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/himatika
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        use_sql_comments: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB